spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: RM550893
    password: 070704
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create
